module.exports = [
  "Quantum physics",
  "Pineapple on pizza",
  "Alien invasion",
  "Existential dread",
  "Gluten-free",
  "Plot twist",
  "Spontaneous combustion",
  "Secret agent",
  "Bermuda Triangle",
  "Golden retriever energy",
  "Awkward silence",
  "Time travel",
  "Emotional damage",
  "Main character energy",
  "Parallel universe",
  "Disco fever",
  "Flat Earth",
  "Conspiracy theory",
  "Cryptocurrency",
  "Dramatic exit",
  "Midlife crisis",
  "Hypnotic trance",
  "Superpower",
  "Illuminati"
];
